create or replace force view bdevices as
select ENODES."NODE_ID",ENODES."SENDER_ID",ENODES."MPOINT_CODE",ENODES."MPOINT_NAME",ENODES."ID_DEV",ENODES."ID_MASK",ENODES."NPIP",ENODES."NPPASSWORD",ENODES."NPQUERY",ENODES."NPLOCK",ENODES."HIDEROW",ENODES."TRANSPORT",ENODES."IPPORT",ENODES."NOCPORT",ENODES."SRV_IP_ID",ENODES."CALLERID",ENODES."HOURSHIFT",ENODES."CFIO1",ENODES."CPHONE1",ENODES."CFIO2",ENODES."CPHONE2",ENODES."CADDRESS",ENODES."ID_MASKSUM",ENODES."MAPX",ENODES."MAPY",ENODES."FULLADDRESS",ENODES."ID_MASKDAY",ENODES."NETADDR", ENODES.NODE_ID  ID_BD
    from ENODES;

