--
-- Скрипт сгенерирован Devart dbForge Studio for Oracle, Версия 3.10.12.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/oracle/studio
-- Дата скрипта: 30.05.2017 13:59:09
-- Версия сервера: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Версия клиента: 
--

SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+03:00';

INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(772, 'Калининград_');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(412, 'Мурманский филиал_');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(472, 'Мурманский филиал');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(952, 'SNTPORTAL');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(112, 'ОАО ''Северо-Западный Телеком'' Вологодский филиал');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(352, 'СПБ');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(532, 'Коми филиал');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(892, 'Мурманский филиал');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(232, 'Калиниградский филиал');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(292, 'Карельский филиал');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(712, 'Аскуэ спб');
INSERT INTO BEAVIS.BGROUPS(ID_GRP, CGRPNM) VALUES
(832, 'Калининградский филиал');

COMMIT;