--
-- Скрипт сгенерирован Devart dbForge Studio for Oracle, Версия 3.10.12.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/oracle/studio
-- Дата скрипта: 30.05.2017 13:59:10
-- Версия сервера: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Версия клиента: 
--

SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+03:00';

INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(1, 7734, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(2, 7737, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(3, 7731, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(4, 7725, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(10, 26058, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(9, 26055, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(11, 26061, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(8, 6723, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(12, 26064, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(32, 38850, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(33, 38853, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(34, 38856, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(38, 57513, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(13, 30483, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(14, 30486, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(15, 27561, NULL, '2400', '0', NULL, '0', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(36, 46704, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(37, 46707, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(41, 63351, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(42, 63354, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(18, 11529, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(19, 15606, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(20, 30165, NULL, '2400', '0', NULL, '0', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(21, 30168, NULL, '2400', '0', NULL, '0', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(22, 7809, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(39, 57516, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(40, 63348, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(16, 11214, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(17, 27558, NULL, '2400', '0', NULL, '0', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(23, 30642, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(24, 32286, NULL, '2400', '0', NULL, '0', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(25, 32187, NULL, '2400', '0', NULL, '0', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(26, 35121, NULL, '2400', '0', NULL, '0', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(27, 33021, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(28, 38163, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(30, 38844, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(31, 38847, NULL, '9600', '8', 'N', '1', NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(35, 6909, NULL, '2400', NULL, NULL, NULL, NULL, 60, 15);
INSERT INTO BEAVIS.BMODEMS(ID_MODEM, ID_BD, CPHONE, CSPEED, CDATABIT, CPARITY, CSTOPBITS, CPREFPHONE, CONNECTLIMIT, PARAMLIMIT) VALUES
(43, 75798, NULL, '9600', '8', 'N', '1', NULL, 60, 15);

COMMIT;