--
-- Скрипт сгенерирован Devart dbForge Studio for Oracle, Версия 3.10.12.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/oracle/studio
-- Дата скрипта: 30.05.2017 13:59:10
-- Версия сервера: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Версия клиента: 
--

SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+03:00';

INSERT INTO BEAVIS.DEVICES(ID_DEV, CDEVNAME, CDEVDESC, ID_CLASS, DLLNAME) VALUES
(2, 'M230', 'Меркурий 230', NULL, 'DrvM230');
INSERT INTO BEAVIS.DEVICES(ID_DEV, CDEVNAME, CDEVDESC, ID_CLASS, DLLNAME) VALUES
(3, 'Unknown', 'Не установлено', NULL, NULL);
INSERT INTO BEAVIS.DEVICES(ID_DEV, CDEVNAME, CDEVDESC, ID_CLASS, DLLNAME) VALUES
(4, 'EuroAlpha', 'Евро альфа', NULL, 'DrvEA');
INSERT INTO BEAVIS.DEVICES(ID_DEV, CDEVNAME, CDEVDESC, ID_CLASS, DLLNAME) VALUES
(5, 'РТК-01', 'РТК-01 ( МИРТЕК)', NULL, 'DrvRTK01');

COMMIT;