--
-- Скрипт сгенерирован Devart dbForge Studio for Oracle, Версия 3.10.12.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/oracle/studio
-- Дата скрипта: 30.05.2017 13:59:12
-- Версия сервера: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Версия клиента: 
--

SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+03:00';

INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(118, 2, 'AP0', 'A+ Sum', NULL, NULL, NULL, 13, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(119, 2, 'AP1', 'A+ 1', NULL, NULL, NULL, 15, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(120, 2, 'AP2', 'A+ 2', NULL, NULL, NULL, 17, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(121, 2, 'AP3', 'A+ 3', NULL, NULL, NULL, 19, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(122, 2, 'RP0', 'R + Sum', NULL, NULL, NULL, 21, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(123, 2, 'RP1', 'R+ 1', NULL, NULL, NULL, 23, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(124, 2, 'RP2', 'R+ 2', NULL, NULL, NULL, 25, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(125, 2, 'RP3', 'R+ 3', NULL, NULL, NULL, 27, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(126, 2, 'AM0', 'A- Sum', NULL, NULL, NULL, 29, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(127, 2, 'AM1', 'A- 1', NULL, NULL, NULL, 31, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(128, 2, 'AM2', 'A- 2', NULL, NULL, NULL, 33, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(129, 2, 'AM3', 'A- 3', NULL, NULL, NULL, 35, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(130, 2, 'RM0', 'R- Sum', NULL, NULL, NULL, 37, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(131, 2, 'RM1', 'R- 1', NULL, NULL, NULL, 39, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(132, 2, 'RM2', 'R- 2', NULL, NULL, NULL, 41, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(133, 2, 'RM3', 'R- 3', NULL, NULL, NULL, 43, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(91, 2, 'T1', 'T1', NULL, NULL, NULL, 3, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(92, 2, 'T2', 'T2', NULL, NULL, NULL, 5, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(93, 2, 'T3', 'T3', NULL, NULL, NULL, 7, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(94, 2, 'T4', 'T4', NULL, NULL, NULL, 9, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(95, 2, 'T5', 'T5', NULL, NULL, NULL, 11, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(111, 2, 'T0', 'T Sum', NULL, NULL, NULL, 1, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(75, 1, 'T2', 'T сут 2', NULL, NULL, NULL, 5, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(135, 1, 'P1', 'P1', NULL, NULL, NULL, 21, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(77, 1, 'U1', 'U1', NULL, NULL, NULL, 7, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(78, 1, 'U2', 'U2', NULL, NULL, NULL, 9, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(79, 1, 'U3', 'U3', NULL, NULL, NULL, 11, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(134, 1, 'P0', 'P sum', NULL, NULL, NULL, 19, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(81, 1, 'I1', 'I1', NULL, NULL, NULL, 13, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(82, 1, 'I2', 'I2', NULL, NULL, NULL, 15, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(83, 1, 'I3', 'I3', NULL, NULL, NULL, 17, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(84, 1, 'G0', 'G sum', NULL, NULL, NULL, 27, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(85, 1, 'G1', 'G1', NULL, NULL, NULL, 29, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(86, 1, 'G2', 'G2', NULL, NULL, NULL, 31, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(136, 1, 'P2', 'P2', NULL, NULL, NULL, 23, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(137, 1, 'P3', 'P3', NULL, NULL, NULL, 25, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(144, 3, 'P1', 'P1', NULL, NULL, NULL, 1, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(145, 3, 'P2', 'P2', NULL, NULL, NULL, 3, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(146, 3, 'P3', 'P3', NULL, NULL, NULL, 5, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(147, 3, 'G0', 'G0', NULL, NULL, NULL, 7, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(148, 3, 'G1', 'G1', NULL, NULL, NULL, 9, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(149, 3, 'G2', 'G2', NULL, NULL, NULL, 11, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(150, 3, 'G3', 'G3', NULL, NULL, NULL, 13, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(155, 3, 'U1', 'U1', NULL, NULL, NULL, 15, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(156, 3, 'U2', 'U2', NULL, NULL, NULL, 17, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(157, 3, 'U3', 'U3', NULL, NULL, NULL, 19, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(158, 3, 'I1', 'I1', NULL, NULL, NULL, 21, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(159, 3, 'I2', 'I2', NULL, NULL, NULL, 23, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(160, 3, 'I3', 'I3', NULL, NULL, NULL, 25, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(161, 3, 'AP0', 'AP0', NULL, NULL, NULL, 27, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(162, 3, 'AP1', 'AP1', NULL, NULL, NULL, 31, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(163, 3, 'AP2', 'AP2', NULL, NULL, NULL, 33, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(164, 3, 'AP3', 'AP3', NULL, NULL, NULL, 35, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(165, 3, 'RP0', 'RP0', NULL, NULL, NULL, 37, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(166, 3, 'RP1', 'RP1', NULL, NULL, NULL, 39, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(167, 3, 'RP2', 'RP2', NULL, NULL, NULL, 41, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(168, 3, 'RP3', 'RP3', NULL, NULL, NULL, 43, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(169, 3, 'AM0', 'AM0', NULL, NULL, NULL, 45, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(170, 3, 'AM1', 'AM1', NULL, NULL, NULL, 47, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(171, 3, 'AM2', 'AM2', NULL, NULL, NULL, 49, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(172, 3, 'AM3', 'AM3', NULL, NULL, NULL, 51, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(173, 3, 'RM0', 'RM0', NULL, NULL, NULL, 53, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(174, 3, 'RM1', 'RM1', NULL, NULL, NULL, 55, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(175, 3, 'RM2', 'RM2', NULL, NULL, NULL, 57, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(176, 3, 'RM3', 'RM3', NULL, NULL, NULL, 30, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(183, 4, 'P1', 'P1', NULL, NULL, NULL, 1, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(184, 4, 'P2', 'P2', NULL, NULL, NULL, 3, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(185, 4, 'P3', 'P3', NULL, NULL, NULL, 5, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(186, 4, 'G0', 'G0', NULL, NULL, NULL, 7, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(187, 4, 'G1', 'G1', NULL, NULL, NULL, 9, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(188, 4, 'G2', 'G2', NULL, NULL, NULL, 11, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(189, 4, 'G3', 'G3', NULL, NULL, NULL, 13, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(190, 4, 'G4', 'G4', NULL, NULL, NULL, 15, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(191, 4, 'G5', 'G5', NULL, NULL, NULL, 17, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(194, 4, 'AP0', 'AP0', NULL, NULL, NULL, 21, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(195, 4, 'AP1', 'AP1', NULL, NULL, NULL, 23, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(196, 4, 'AP2', 'AP2', NULL, NULL, NULL, 25, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(197, 4, 'AP3', 'AP3', NULL, NULL, NULL, 27, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(198, 4, 'RP0', 'RP0', NULL, NULL, NULL, 29, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(199, 4, 'RP1', 'RP1', NULL, NULL, NULL, 31, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(200, 4, 'RP2', 'RP2', NULL, NULL, NULL, 33, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(73, 1, 'T0', 'T сут.  sum', NULL, NULL, NULL, 1, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(74, 1, 'T1', 'T сут 1', NULL, NULL, NULL, 3, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(201, 4, 'RP3', 'RP3', NULL, NULL, NULL, 35, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(202, 4, 'AM0', 'AM0', NULL, NULL, NULL, 37, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(203, 4, 'AM1', 'AM1', NULL, NULL, NULL, 39, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(204, 4, 'AM2', 'AM2', NULL, NULL, NULL, 41, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(205, 4, 'AM3', 'AM3', NULL, NULL, NULL, 43, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(206, 4, 'RM0', 'RM0', NULL, NULL, NULL, 45, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(207, 4, 'RM1', 'RM1', NULL, NULL, NULL, 47, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(208, 4, 'RM2', 'RM2', NULL, NULL, NULL, 49, 80, 'N', 0);
INSERT INTO BEAVIS.MASKSLINE(ID_MASKL, ID_MASK, CFLD, CHEADER, DENTER, ID_USR, ID_TYPE, SEQUENCE, COLWIDTH, COLFORMAT, COLHIDDEN) VALUES
(209, 4, 'RM3', 'RM3', NULL, NULL, NULL, 19, 80, 'N', 0);

COMMIT;