--
-- Скрипт сгенерирован Devart dbForge Studio for Oracle, Версия 3.10.12.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/oracle/studio
-- Дата скрипта: 30.05.2017 13:59:13
-- Версия сервера: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Версия клиента: 
--

SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+03:00';

INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(20, 'Иванов', 40);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(464, 'Сидоров', 40);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(467, 'Комаровский', 80);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(469, 'Михальчик', 80);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(471, 'Балаганов', 82);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(473, 'Куприянов', 80);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(475, 'Архипенко', 82);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(477, 'Остенбакен', 40);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(479, 'Зайонц', 82);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(481, 'Паниковский', 82);
INSERT INTO BEAVIS.TBL(SID, SNAME, DEPNO) VALUES
(483, 'Корейко', 82);

COMMIT;