--
-- Скрипт сгенерирован Devart dbForge Studio for Oracle, Версия 3.10.12.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/oracle/studio
-- Дата скрипта: 30.05.2017 13:59:13
-- Версия сервера: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Версия клиента: 
--

SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+03:00';

INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(9, 'mailer', 'mailer', 0, 'vmb@astrum.spb.ru');
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(13, 'mail3', 'mail3', 0, 'Vitaliy.Kashtanov@nw.rt.ru');
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(11, 'mail1', 'mail1', 0, 'A.Shkryl@nw.rt.ru');
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(12, 'mail2', 'mail2', 0, 'Denis.Markov@nw.rt.ru');
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(14, 'mail4', 'mail4', 0, 'Semenova.ol@astrum.spb.ru');
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(8, 'askue', 'askue', 0, NULL);
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(7, 'murman', 'murman', 0, NULL);
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(10, 'boss', 'boss', 0, NULL);
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(2, 'spb', 'spb', 0, 'piter_bo@astrum.spb.ru');
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(3, 'vol', 'vol', 0, NULL);
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(4, 'all', 'all', 0, 'bami@nm.ru');
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(5, 'kalin', 'kalin', 0, NULL);
INSERT INTO BEAVIS.USERS(USERSID, LOGIN, PASSWORD, LOCKED, EMAIL) VALUES
(6, 'kar', 'kar', 0, NULL);

COMMIT;