--
-- Скрипт сгенерирован Devart dbForge Studio for Oracle, Версия 3.10.12.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/oracle/studio
-- Дата скрипта: 30.05.2017 13:59:13
-- Версия сервера: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Версия клиента: 
--

SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+03:00';

INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(1, 352);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(2, 352);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(2, 712);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(2, 952);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(3, 112);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 112);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 232);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 292);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 352);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 412);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 472);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 532);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 712);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 772);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 832);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 892);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(4, 952);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(5, 232);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(6, 292);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(7, 412);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(7, 472);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(8, 712);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(9, 352);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(9, 712);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(9, 952);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(10, 352);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(10, 712);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(10, 952);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(11, 352);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(11, 712);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(11, 952);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(12, 352);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(12, 712);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(12, 952);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(13, 352);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(13, 952);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(14, 352);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(14, 712);
INSERT INTO BEAVIS.USERGROUP(USERSID, ID_GRP) VALUES
(14, 952);

COMMIT;